version: '3.9'

services:
  main_service:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    volumes:
      - .:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - ./.env.dev
    depends_on:
      - database
  database:
      image: postgres
      restart: always
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      environment:
        POSTGRES_HOST_AUTH_METHOD: trust
        POSTGRES_PASSWORD: postgres
      ports:
        - 5432:5432

volumes:
  postgres_data: