version: '3.9'

services:
  janus:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    volumes:
      - .:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - ./.env.dev
    depends_on:
      - janus-db
  janus-db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data: