# Generated by Django 4.1.3 on 2023-06-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_image_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reply_user',
            new_name='ReplyUser',
        ),
    ]
