# Generated by Django 4.1.3 on 2023-07-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_question_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='owner_id',
        ),
    ]
