# Generated by Django 4.1.3 on 2023-08-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_answer_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
