# Generated by Django 4.1.3 on 2023-08-09 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_notification_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncategory',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.question'),
        ),
        migrations.AlterField(
            model_name='questiontag',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.question'),
        ),
    ]
