# Generated by Django 4.1.3 on 2023-08-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_devicetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForbiddenWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
