# Generated by Django 4.1.3 on 2023-08-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_forbiddenword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeruser',
            name='is_dislike',
        ),
        migrations.RemoveField(
            model_name='questionuser',
            name='is_dislike',
        ),
        migrations.RemoveField(
            model_name='replyuser',
            name='is_dislike',
        ),
    ]
