# Generated by Django 4.1.3 on 2023-08-17 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_answeruser_is_dislike_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeruser',
            name='question_id',
        ),
        migrations.AddField(
            model_name='answeruser',
            name='answer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.answer'),
        ),
    ]
